### ISSUE TITLE
Facebook Audience resigning error

### ISSUE THREAD

**Issue by arcreature7** [distriqt/ANE-Adverts-Mediation#19]
Hi,

I build ipa on windows and then run the resign script on mac, but I get an error.
It was built as a development version.

> Create Signing Entitlements
> Print: Entry, "Entitlements:beta-reports-active", Does Not Exist
> 	APP_NAME = ZombieSweeper.app
> 	TEAM_IDENTIFIER = 5XHXXXXZX6
> 	APPLICATION_IDENTIFIER_PREFIX = 5XHXXXXZX6
> 	BUNDLE_IDENTIFIER = com.arcgamestudio.zombiesweeper
> 	APS_ENVIRONMENT = development
> 	BETA_REPORTS = 
> 	PROVISIONING_GET_TASK_ALLOW = true
> File Doesn't Exist, Will Create: ./Entitlements.plist
> Setting aps-environment=development
> Sign Frameworks
> .tmp/Payload/ZombieSweeper.app/Frameworks/FBAudienceNetwork.framework: replacing existing signature
> Warning: unable to build chain to self-signed root for signer "iPhone Developer: Wonho Lim (R2XXXXX922)"
> .tmp/Payload/ZombieSweeper.app/Frameworks/FBAudienceNetwork.framework: errSecInternalComponent
> Sign Application
> .tmp/Payload/ZombieSweeper.app: replacing existing signature
> Warning: unable to build chain to self-signed root for signer "iPhone Developer: Wonho Lim (R2XXXXX922)"
> .tmp/Payload/ZombieSweeper.app: errSecInternalComponent
> .tmp/Payload/ZombieSweeper.app: invalid resource directory (directory or signature have been modified)

Is a resign required to apply FacebookAudience to iOS?
Is this an AIR issue? I didn't quite understand why this procedure was necessary.

I checked issue [#17 (Facebook resign is not working)](https://github.com/distriqt/ANE-Adverts-Mediation/issues/17), deleted all .DS_Store files and tried again,
but the issue was not resolved.

I need your advice.

**Comment by marchbold** [comment]
Hi,

Yeah this is an AIR issue, some dynamic Frameworks don't seem to get signed correctly. I'll raise this again with Harman to see if we can finally get it resolved. 

Regarding your specific case I'm not exactly sure what the issue is, everytime I've seen that error around `invalid resource directory (directory or signature have been modified)` it has been due to a file being placed into the framework incorrectly. 

Try downloading the framework from the repository again and double checking that there are no other files (including .DS_Store) appearing in the directory.

**Comment by pitanello** [comment]
Same problem here, Apple doesn't like the new resigned IPA.
Could my old version of Xcode be a problem in this process of resigning the IPA?

**Comment by marchbold** [comment]
Could be, the script utilises xcode utilities to sign, so would highly recommend using the latest or at least v12.
