### ISSUE TITLE
 Сrash. FAN Adapter

### ISSUE THREAD

**Issue by Dima107** [distriqt/ANE-Adverts-Mediation#48]
The app crashing when trying to open the game on the iPad Air
Air SDK 929
Devices + OS: iPad Air (11.4.1)
ANEs version - latest

if don't add FAN I have no issue.

Log contains few lines with errors. They contains "FBApplicationProcess"

I don't use Facebook.ane for my app
[iPad AIR error log.txt](https://github.com/distriqt/ANE-Adverts-Mediation/files/9414541/iPad.AIR.error.log.txt)

List of ANEs
[anes.txt](https://github.com/distriqt/ANE-Adverts-Mediation/files/9414576/anes.txt)

**Comment by marchbold** [comment]
FBApplicationProcess is not actually related to Facebook despite the `FB` prefix, it is actually an iOS class.

Could you post the crash log as well, there doesn't appear to be any information in the console log?

Generally my guess here if the crash is caused by adding the audience network ane would be that you haven't packaged the dynamic frameworks in your application. Check the docs on adding the dynamic framework:

https://docs.airnativeextensions.com/docs/adverts/mediation/facebookaudience#add-the-extension

**Comment by Dima107** [comment]
Dynamic frameworks were added. I'm sure. If I don't add them crash happens on all devices

Crash happens only on one of our devices. -  Device + OS: iPad Air (11.4.1)

This log sent me tester. He says it's a crash log. I have no another log

**Comment by marchbold** [comment]
Are you including the swift libs in the Frameworks folder? 

If you support versions of ios < 12 you need to include the swift libs as well. 

Generally we advise using 12 as the minimum these days but if you need to support older version you need to include them.

**Comment by Dima107** [comment]
Ok. Thank you

Can you help me to find correct versions of swift libs?

**Comment by marchbold** [comment]
Try these ones: 

https://drive.google.com/file/d/1lugqX2B_QigdWiiK7bsnz_eiS__--Dpf/view?usp=sharing

You need to include them in your Frameworks directory.

**Comment by Dima107** [comment]
thank you
